Complete redo - plain and simple
Places an rc file in vendor/etc/init if it exists. Otherwise placed in system/etc/init

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,66 +1,79 @@
 #!/sbin/sh
-# AnyKernel2 Backend
-# osm0sis @ xda-developers
+#Setup
+ZIP=/dev/tmp/install
+rm -rf /dev/tmp 2>/dev/null
+mkdir -p $ZIP
+unzip -o "$3" -d $ZIP 2>/dev/null
+OUTFD=$2
+readlink /proc/$$/fd/$OUTFD 2>/dev/null | grep /tmp >/dev/null
+if [ "$?" -eq "0" ]; then
+  OUTFD=0
+  for FD in `ls /proc/$$/fd`; do
+    readlink /proc/$$/fd/$FD 2>/dev/null | grep pipe >/dev/null
+    if [ "$?" -eq "0" ]; then
+      ps | grep " 3 $FD " | grep -v grep >/dev/null
+      if [ "$?" -eq "0" ]; then
+        OUTFD=$FD
+        break
+      fi
+    fi
+  done
+fi
 
-OUTFD=/proc/self/fd/$2;
-ZIPFILE="$3";
-DIR=`dirname "$ZIPFILE"`;
-
+#Functions
 ui_print() {
-  until [ ! "$1" ]; do
-    echo -e "ui_print $1\nui_print" > $OUTFD;
-    shift;
-  done;
+  echo -e "ui_print $1\nui_print" >> /proc/self/fd/$OUTFD
 }
-show_progress() { echo "progress $1 $2" > $OUTFD; }
-file_getprop() { grep "^$2=" "$1" | cut -d= -f2; }
-if [ ! "$(getprop 2>/dev/null)" ]; then
-  getprop() {
-    local propval="$(file_getprop /default.prop $1 2>/dev/null)";
-    test "$propval" || local propval="$(file_getprop /system/build.prop $1 2>/dev/null)";
-    test "$propval" && echo "$propval" || echo "";
-  }
-fi;
-cleanup() { rm -rf /tmp/anykernel; }
-debugging() {
-  case $(basename "$ZIPFILE" .zip) in
-    *-debugging)
-      ui_print " ";
-      ui_print "Creating debugging archive in zip directory...";
-      $bb tar -czvf "$DIR/anykernel2-$(date +%Y-%m-%d_%H%M%S)-debug.tgz" /tmp/*;
-    ;;
-    *-uninstall)
-      ACTION=Uninstall;
-    ;;
-  esac;
+
+find_boot_image() {
+  BOOTIMAGE=
+  if [ ! -z $SLOT ]; then
+    BOOTIMAGE=`find /dev/block -iname boot$SLOT | head -n 1` 2>/dev/null
+  fi
+  if [ -z $BOOTIMAGE ]; then
+    # The slot info is incorrect...
+    SLOT=
+    for BLOCK in ramdisk boot_a kern-a android_boot kernel boot lnx bootimg; do
+      BOOTIMAGE=`find /dev/block -iname $BLOCK | head -n 1` 2>/dev/null
+      [ ! -z $BOOTIMAGE ] && break
+    done
+  fi
+  # Recovery fallback
+  if [ -z $BOOTIMAGE ]; then
+    for FSTAB in /etc/*fstab*; do
+      BOOTIMAGE=`grep -v '#' $FSTAB | grep -E '/boot[^a-zA-Z]' | grep -oE '/dev/[a-zA-Z0-9_./-]*'`
+      [ ! -z $BOOTIMAGE ] && break
+    done
+  fi
+  [ ! -z $BOOTIMAGE ] && BOOTIMAGE=`readlink -f $BOOTIMAGE`
 }
-abort() {
-  ui_print "$*";
-  debugging;
-  if [ ! -f /tmp/anykernel/anykernel.sh -o "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanuponabort 2>/dev/null)" == 1 ]; then
-    cleanup;
-  fi;
-  umount -l /system_root 2>/dev/null
-  umount -l /system 2>/dev/null
-  umount -l /vendor 2>/dev/null                      
-  exit 1;
+
+find_dtbo_image() {
+  DTBOIMAGE=`find /dev/block -iname dtbo$SLOT | head -n 1` 2>/dev/null
+  [ ! -z $DTBOIMAGE ] && DTBOIMAGE=`readlink -f $DTBOIMAGE`
 }
+
 is_mounted() {
   TARGET="`readlink -f $1`"
   cat /proc/mounts | grep " $TARGET " >/dev/null
   return $?
 }
-mount_system() { 
+
+mount_partitions() {
   # Check A/B slot
-  slot=`getprop ro.boot.slot_suffix`
-  if [ -z $slot ]; then
-    slot=_`getprop ro.boot.slot`
-    [ $slot = "_" ] && slot=
+  SLOT=`getprop ro.boot.slot_suffix`
+  if [ -z $SLOT ]; then
+    SLOT=_`getprop ro.boot.slot`
+    [ $SLOT = "_" ] && SLOT=
   fi
-  [ -z $slot ] || ui_print "A/B partition detected, current slot: $slot"
+  # Check the boot image to make sure the slot actually make sense
+  find_boot_image
+  find_dtbo_image
+  [ -z $SLOT ] || ui_print "A/B partition detected, current slot: $SLOT"
+  ui_print "Mounting /system, /vendor"
   is_mounted /system || [ -f /system/build.prop ] || mount -o rw /system 2>/dev/null
   if ! is_mounted /system && ! [ -f /system/build.prop ]; then
-    SYSTEMBLOCK=`find /dev/block -iname system$slot | head -n 1`
+    SYSTEMBLOCK=`find /dev/block -iname system$SLOT | head -n 1`
     mount -t ext4 -o rw $SYSTEMBLOCK /system
   fi
   is_mounted /system || [ -f /system/build.prop ] || abort "! Cannot mount /system"
@@ -81,95 +94,48 @@ mount_system() {
     fi
     is_mounted /vendor || abort "! Cannot mount /vendor"
   fi
-  ui_print " "
 }
 
-ui_print " ";
-cleanup;
-mkdir -p /tmp/anykernel/bin;
-cd /tmp/anykernel;
-unzip -o "$ZIPFILE";
-if [ $? != 0 -o -z "$(ls /tmp/anykernel/tools)" ]; then
-  abort "Unzip failed. Aborting...";
-fi;
-bb=/tmp/anykernel/tools/busybox;
-chmod 755 $bb;
-$bb chmod -R 755 /tmp/anykernel/tools /tmp/anykernel/bin;
+unmount_partitions() {
+  ui_print "Unmounting partitions"
+  umount -l /system_root 2>/dev/null
+  umount -l /system 2>/dev/null
+  umount -l /vendor 2>/dev/null
+  rm -rf /dev/tmp
+}
 
-if [ -f /tmp/anykernel/banner ]; then
-  while IFS='' read -r line || $bb [[ -n "$line" ]]; do
-    ui_print "$line";
-  done < /tmp/anykernel/banner;
-  ui_print " ";
-  ui_print " ";
-fi;
+abort() {
+  ui_print "$1"
+  unmount_partitions
+  exit 1
+}
 
-ui_print "$(file_getprop /tmp/anykernel/anykernel.sh kernel.string)";
-ui_print "By: Zackptg5 & Shadowstep @ xda-developers"
-if [ -f /tmp/anykernel/version ]; then
-  ui_print " ";
-  ui_print "$(cat /tmp/anykernel/version)";
-  ui_print " ";
-fi;
-ui_print " ";
-ui_print "AnyKernel2 by osm0sis @ xda-developers";
-ui_print " ";
-ui_print " ";
+# Main
+ui_print " "
+ui_print "    *******************************************"
+ui_print "    *    OOS Native Call Recording Enabler    *"
+ui_print "    *******************************************"
+ui_print "    *              by: Zackptg5               *"
+ui_print "    *******************************************"
+ui_print " "
+mount_partitions
+[ "$(grep "ro.build.version.ota=OnePlus" /system/build.prop)" -o "$(grep "ro.product.brand=OnePlus" /system/build.prop)" ] && [ "$(grep "ro.build.version.ota=.*Oxygen" /system/build.prop)" ] || abort "!Unsupported device. Aborting!"
 
-mount_system
-mount /data 2>/dev/null;
+if [ -d /system/vendor/etc/init ]; then
+  DIR=/system/vendor/etc/init
+else
+  DIR=/system/etc/init
+fi
 
-if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.devicecheck)" == 1 ]; then
-  ui_print "Checking device...";
-  ui_print " ";
-  [ "$(getprop ro.product.manufacturer)" == "OnePlus" -o "$(getprop ro.product.brand)" == "OnePlus)" ] || abort "Unsupported device. Aborting...";
-  ui_print "OnePlus device detected!"
-  ui_print " ";
-fi;
+if [ -f "$DIR/init.ncr.rc" ]; then
+  ui_print "Removing native call recording"
+  rm -f $DIR/init.ncr.rc
+else
+  ui_print "Adding native call recording"
+  cp -f $ZIP/init.ncr.rc $DIR/init.ncr.rc
+  chmod 0644 $DIR/init.ncr.rc
+  chcon u:object_r:vendor_configs_file:s0 $DIR/init.ncr.rc
+fi
 
-for i in $($bb --list); do
-  $bb ln -s $bb /tmp/anykernel/bin/$i;
-done;
-if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
-  abort "Recovery busybox setup failed. Aborting...";
-fi;
-if [ -z $slot ]; then sed -i "/<ACTION>/d" /tmp/anykernel/tools/ak2-core.sh; else sed -i "s|<ACTION>|$ACTION|" /tmp/anykernel/tools/ak2-core.sh; fi
-if [ -z $slot ]; then sed -i "/<slot>/d" /tmp/anykernel/tools/ak2-core.sh; else sed -i "s|<slot>|$slot|" /tmp/anykernel/tools/ak2-core.sh; fi
-PATH="/tmp/anykernel/bin:$PATH" $bb ash /tmp/anykernel/anykernel.sh $2;
-if [ $? != "0" ]; then
-  abort;
-fi;
-
-if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.modules)" == 1 ]; then
-  ui_print " ";
-  ui_print "Pushing modules...";                                                 
-  cd /tmp/anykernel/modules;
-  for module in $(find . -name '*.ko'); do
-   if [ ! -e /$module ]; then
-      case $module in
-        */vendor/*) mod=vendor;;
-        *) mod=system;;
-      esac;
-    fi;
-    $bb cp -rLf $module /$module;
-    $bb chown 0:0 /$module;
-    $bb chmod 644 /$module;
-    if [ "$mod" ]; then
-      chcon "u:object_r:${mod}_file:s0" /$module;
-    fi;
-  done;
-  cd /tmp/anykernel;                                          
-fi;
-
-debugging;
-
-if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanup)" == 1 ]; then
-  cleanup;
-fi;
-
-umount -l /system_root 2>/dev/null
-umount -l /system 2>/dev/null
-umount -l /vendor 2>/dev/null                            
-ui_print " ";
-ui_print " ";
-ui_print "Done!";
+unmount_partitions
+exit 0
